'use strict';

const chai = require('chai');

const expect = chai.expect;
const Support = require('../../support');

const { DataTypes } = require('@sequelize/core');

const dialect = Support.getTestDialect();

if (dialect.startsWith('postgres')) {
  describe('[POSTGRES Specific] Regressions', () => {
    it('properly fetch OIDs after sync, #8749', async function () {
      const User = this.sequelize.define('User', {
        active: DataTypes.BOOLEAN,
      });

      /**
       * This Model is important, sync will try to fetch OIDs after each ENUM model sync
       * Having ENUM in this model will force OIDs re-fetch
       * We are testing that OID refresh keep base type intact
       */
      const Media = this.sequelize.define('Media', {
        type: DataTypes.ENUM(['image', 'video', 'audio']),
      });

      User.hasMany(Media);
      Media.belongsTo(User);

      await this.sequelize.sync({ force: true });

      const user1 = await User.create({ active: true });
      expect(user1.active).to.be.true;
      expect(user1.get('active')).to.be.true;

      const user0 = await User.findOne();
      expect(user0.active).to.be.true;
      expect(user0.get('active')).to.be.true;

      const user = await User.findOne({ raw: true });
      expect(user.active).to.be.true;
    });

    // test for issue where dropTable generates invalid SQL code when passed a model object
    it('generate valid SQL calling dropTable using a model object', async function () {
      // example invalid SQL code (note the "class extends" part):
      /*
      DROP TABLE IF EXISTS "enum_test_tables" CASCADE
      DROP TYPE IF EXISTS "public"."enum_class extends import_model.Model {
}_testEnum"; : expected 'Executing (default): DROP TABLE IF EX…' to not include 'class extends'
    */
      const tableName = 'enum_test_table';

      // Define a model to test against
      const EnumTestTable = this.sequelize.define(tableName, {
        id: {
          type: DataTypes.INTEGER,
          primaryKey: true,
          autoIncrement: true,
        },
        testEnum: {
          type: DataTypes.ENUM('foo', 'bar'),
          allowNull: false,
          field: 'test_enum',
        },
      });

      // Sync the model to create the table
      await EnumTestTable.sync({ force: true });

      // Retrieve the model object using the defined name
      const table = this.sequelize.models.get(tableName);
      expect(table).to.exist;

      // call method to drop the table using the model object
      const sqlCode = [];
      await this.sequelize.queryInterface.dropTable(table, {
        cascade: true,
        // gather all SQL code generated by the query interface when syncing
        logging: sql => sqlCode.push(sql),
      });

      // Check that the SQL code does not include "class extends"
      //  This can happen when passing a model to dropTable,
      //  where the whole class gets turned into a string
      const sql = sqlCode.join('\n');
      expect(sql).to.not.include(
        'class extends',
        `dropTable should not include JS code in generated SQL command. Generated code:\n${sql}`,
      );
    });
  });
}
